import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "MySousApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="body">
        <Navbar />

        {children}
      </body>
    </html>
  );
}
