import "./globals.css";
import Navbar from "./components/Navbar";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import AuthContext from "./AuthContext";

import Toaster from "./toaster";

export const metadata = {
  title: "MySousApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className="body">
          <AuthContext>
            <Toaster />
            <Navbar />
            <RegisterModal />
            <LoginModal />

            {children}
          </AuthContext>
        </body>
      </html>
    </>
  );
}
